import { Activity, BarChart3, Bot, Clock3, Home, ListMusic, Music2, Pause, Play, Search, Settings, SkipBack, SkipForward, Square, Users } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { requireUser, can } from '@/lib/auth';
import { LogoutButton } from './logout-button';

export default async function DashboardPage(){
  const user=await requireUser(); const items: Array<[LucideIcon,string]>=[[Home,'Home'],[Search,'Search'],[ListMusic,'Queue'],[BarChart3,'Stats'],[Bot,'Bot'],...(can(user.role,'manageUsers')?[[Users,'Users'] as [LucideIcon,string]]:[]),[Settings,'Settings']];
  return <div className="shell"><aside><div className="side-brand"><span><Music2/></span><div><b>Lomuyayo</b><small>Music</small></div></div><nav>{items.map(([Icon,label],i)=><button className={i===0?'active':''} key={label}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="agent-mini"><i/><div><b>Oracle Agent</b><small>Awaiting heartbeat</small></div></div></aside><main className="workspace"><header><div><p className="kicker">MUSIC CONTROL PLANE</p><h1>Good evening, {user.username}</h1></div><div className="top-actions"><span className="offline">● AGENT OFFLINE</span><div className="avatar">{user.username.slice(0,2).toUpperCase()}</div><div><b>{user.username}</b><small>{user.role.replace('_',' ')}</small></div><LogoutButton/></div></header>{user.mustChangePassword&&<div className="notice">Your initial password is temporary. Change it from Settings before using production controls.</div>}<section className="now-card"><div className="art"><Music2 size={58}/></div><div className="track"><p className="kicker">NOW PLAYING</p><h2>Agent unavailable</h2><p className="muted">Connect the Oracle Bot Agent to load the active guild and player.</p><div className="timeline"><i/></div><div className="time"><span>0:00</span><span>0:00</span></div><div className="player-controls"><button disabled><SkipBack/></button><button className="play" disabled><Play/></button><button disabled><Pause/></button><button disabled><SkipForward/></button><button disabled><Square/></button></div></div><div className="lifecycle"><span className="sleep-icon"><Bot/></span><p className="kicker">BOT LIFECYCLE</p><h3>Offline</h3><p>Waiting for a secure heartbeat from Oracle.</p><button disabled>Wake bot</button></div></section><section className="stats-grid"><article><Activity/><div><span>STATUS</span><b>Offline</b></div></article><article><ListMusic/><div><span>IN QUEUE</span><b>—</b></div></article><article><Clock3/><div><span>UPTIME</span><b>—</b></div></article><article><Users/><div><span>GUILD</span><b>Not selected</b></div></article></section><section className="lower"><article><div className="section-head"><div><p className="kicker">UP NEXT</p><h3>Queue</h3></div><button disabled>Open queue</button></div><div className="empty"><ListMusic/><b>No queue available</b><p>Tracks will appear after the Agent connects.</p></div></article><article><div className="section-head"><div><p className="kicker">ACTIVITY</p><h3>Recent events</h3></div></div><div className="empty"><Activity/><b>No events yet</b><p>Secure actions and lifecycle events appear here.</p></div></article></section></main></div>
}
